import static com.kazurayam.junit4ks.JUnitCustomKeywords.runWithJUnitRunner

import com.kazurayam.ks.testclosure.TestClosureCollectionExecutor2Test

runWithJUnitRunner(TestClosureCollectionExecutor2Test.class)