import static com.kazurayam.junit4ks.JUnitCustomKeywords.runWithJUnitRunner

import com.kazurayam.testclosure.TestClosureCollectionExecutorTest

runWithJUnitRunner(TestClosureCollectionExecutorTest.class)