import static com.kazurayam.junit4ks.JUnitCustomKeywords.runWithJUnitRunner

import com.kazurayam.ks.windowlayout.TilingWindowLayoutMetricsTest

runWithJUnitRunner(TilingWindowLayoutMetricsTest.class)