import static com.kazurayam.junit4ks.JUnitCustomKeywords.runWithJUnitRunner

import com.kazurayam.ks.windowlayout.BrowserWindowLayoutKeywordTest

runWithJUnitRunner(BrowserWindowLayoutKeywordTest.class)
